version: '3.1'
services:
  db:
    image: postgres
    env_file: .env
    container_name: ${PROJ_NAME}_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - web-db:/var/lib/postgresql/data

  backend:
    build: .
    container_name: ${PROJ_NAME}_backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: bash -c "sleep 10 && sh init.sh"
    env_file: .env
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
    links:
      - db
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: ${PROJ_NAME}_nginx
    env_file: .env
    ports:
      - "80:80"
    links:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
    command: /bin/bash -c "sleep 5 && nginx -g 'daemon off;'"
    volumes:
      - ./logs/nginx:/tmp/logs
      - ./nginx:/etc/nginx/conf.d/default.conf
      - ./static:/opt/app/static
      - ./media:/opt/app/media
    depends_on:
      - backend

volumes:
  web-db:
